added mealName property in slack message notifier
kndpio/kndpio pull request #163
Opened 2024-01-24 11:49 UTC by ca7alindev

2024-01-24 15:53 UTC, ca7alindev commented
@web7evgheni please check this PR

2024-01-25 15:33 UTC, web7evgheni requested changes

2024-01-25 15:33 UTC, web7evgheni commented on packages/meal/package/mealxrd.yaml
> +              Title:
@ca7alindev Lowercase please

2024-01-25 15:33 UTC, web7evgheni commented on packages/meal/slack-collector/main.go
> +		if meal.Spec.Title == name {
@ca7alindev Use name for search not Title, Title is used just for messages, because when i will create Meal object, i could enter same Title for many meals, and i will break your app :)

2024-01-25 15:57 UTC, ca7alindev commented on packages/meal/package/mealxrd.yaml
> +              Title:
done

2024-01-25 15:57 UTC, ca7alindev commented on packages/meal/slack-collector/main.go
> +		if meal.Spec.Title == name {
done

2024-02-09 08:09 UTC, web7evgheni approved these changes

2024-02-09 08:09 UTC, merged